I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script
    define m = Character(name=m_name,color="#0000FF")
  File "game/script.rpy", line 25, in <module>
    define m = Character(name=m_name,color="#0000FF")
NameError: name 'm_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script
    define m = Character(name=m_name,color="#0000FF")
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\daruma\use-bin\renpy\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 25, in <module>
    define m = Character(name=m_name,color="#0000FF")
NameError: name 'm_name' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
gizin_kaden 1.0
Mon Jan 29 02:47:50 2024
